PUT https://localhost:7162/breakfasts/aa67ef7a-4d8d-4bb9-8f95-b546b05b6877
Content-Type: application/json

{
  "name": "Vegan Sunshinezzz",
  "description": "Vegan everything! Join us for a healthy breakfast..",
  "startDateTime": "2022-04-08T08:00:00",
  "endDateTime": "2022-04-08T11:00:00",
  "savory": ["Oatmeal", "Avocado Toast", "Omelette", "Salad"],
  "Sweet": ["Cookie"]
}